---
- name: "Build a container with ansible"
  hosts: localhost
  connection: local
  tasks:
    - name: stop current running container
      command: docker stop comingsoon-container
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm comingsoon-container
      ignore_errors: yes

    - name: remove comingsoon-image
      command: docker rmi comingsoon-image
      ignore_errors: yes

    - name: build docker image using the Dockerfile
      command: docker build -t comingsoon-website1-img .

    - name: create tag to image
      command: docker tag comingsoon-website1-img siwarziadi/comingsoon-website1-img

    - name: push image to dockerhub
      command: docker push siwarziadi/comingsoon-website1-img

    - name: remove docker created images
      command: docker rmi  siwarziadi/comingsoon-website1-img
